package com.utilities.dizionari;

import java.util.TreeSet;

public class DizionarioEquipaggiamento {
    private TreeSet<Equipaggiamento> dizionarioEquipaggiamento= new TreeSet<>();

    public DizionarioEquipaggiamento(){
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Abaco","Strumento solitamente in legno, costituito da una cornice rettangolare che contiene delle aste sulle quali scorrono delle palline",1F,"2 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Abito Comune","Abito comune per vestirsi",1.5F,"5 ma"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Abito Costume","Costume per travestirsi",2F,"5 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Abito da Viaggiatore","Abito per viaggiare",2F,"2 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Abito Pregiato","Abito pregiato per vestirsi",3F,"15 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Acciarino e Pietra Focaia","Un piccolo contenitore usato per accendere il fuoco, che contiene acciarino, pietra focaia e materiale combustibile (solitamente stracci essiccati e bagnati d'olio). Per accendere una torcia (o qualsiasi altra cosa che faccia uso di abbondante combustibile scoperto) usando acciarino e pietra focaia è richiesta un'azione. Per accendere un fuoco di qualsiasi altro tipo è richiesto 1 minuto. ",0.5F,"5 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Acido (fiala)","Con un'azione, il personaggio può spruzzare il contenuto di questa fiala su una creatura situata entro 1,5metri da lui o lanciarla fino a 6 metri di distanza (la fiala si frantumerà all'impatto). In ogni caso, il personaggio effettua un attacco a distanza contro una creatura o un oggetto, considerando l'acido come un'arma improvvisata.Se la fiala d'acido colpisce il bersaglio, quest'ultimo subisce2d6 danni da acido",0.5F,"25 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Acqua Santa (ampolla)","Con un'azione, il personaggio può spruzzare il contenuto di questa ampolla su una creatura situata entro 1,5 metri da lui o lanciarla fino a 6 metri di distanza(l'ampolla si frantumerà all'impatto). In ogni caso il personaggio effettua un attacco a distanza contro la creatura bersaglio, considerando l'acqua santa come un'arma improvvisata. Se il bersaglio è un immondo o un non morto, subisce 2d6 danni radiosi.Un chierico o un paladino può creare l'acqua santa celebrando un rituale speciale. Per celebrare questo rituale è richiesta 1 ora di tempo e polvere d'argento per un valore di 25 mo; l'incantatore deve inoltre spendere uno slot incantesimo di 1° livello.",0.5F,"25 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Aghi da cerbottana (50)","Aghi da cerbottana",0.5F,"1 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Ampolla o boccale","Ampolla o boccale",0.5F,"2 mr"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Amuleto","Un simbolo sacro per la rappresentazione di un dio o di un pantheon. Potrebbe essere un amuleto che raffigura il simbolo di una divinità, o uno scudo che porta quel simbolo inciso come emblema, o un minuscolo scrigno contenente il frammento di una reliquia sacra.L'appendice 8 elenca i simboli comunemente associati alla maggior parte delle divinità del multiverso. Un chierico o un paladino può usare un simbolo sacro come focus da incantatore, nel modo descritto nel capitolo 10. Per usare il simbolo in questo modo, l'incantatore deve impugnarlo in modo ben visibile o portarlo su uno scudo",0.5F,"5 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Anello con sigillo","Anello con sigillo",0F,"5 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Antitossina","Una creatura che beve questa fiala di liquido dispone di vantaggio ai tiri salvezza contro veleno per 1 ora.Non conferisce alcun beneficio ai costrutti o ai non morti",0F,"50 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Ariete portatile","Un ariete portatile può essere usato per sfondare le porte e conferisce un bonus di +4 alla prova diForza del personaggio. Un altro personaggio può aiutare il primo a usare l'ariete, nel qual caso il primo personaggio dispone di vantaggio a questa prova",17.5F,"4 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Asta (3 metri)","Asta",0.5F,"5 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Attrezzi da Scalatore","Gli attrezzi da scalatore includono dei chiodi da rocciatore speciali, punte per stivali, guanti e un'imbragatura. Un personaggio può usare gli attrezzi da scalatore con un'azione per ancorarsi;quando lo fa, non può cadere per più di 7,5 metri dal punto in cui si è ancorato e non può arrampicarsi per più di 7,5metri dal quel punto senza disfare l'ancora.",6F,"25 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Bacchetta"," Un focus arcano è un oggetto speciale(una bacchetta in legno, un bastone di fattura speciale,un cristallo, un globo, una verga), creato per incanalare il potere degli incantesimi arcani. Un mago, uno stregone o un warlock può usare questo oggetto come focus da incantatore nel modo descritto nel capitolo 10. ",0.5F,"10 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Barile","Barile",35F,"2 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Bastone"," Un focus arcano è un oggetto speciale(una bacchetta in legno, un bastone di fattura speciale,un cristallo, un globo, una verga), creato per incanalare il potere degli incantesimi arcani. Un mago, uno stregone o un warlock può usare questo oggetto come focus da incantatore nel modo descritto nel capitolo 10. ",2F,"5 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Bastone in Legno di Tasso","Un focus druidico potrebbe essere una bacchetta o uno scettro fatto in legno di tasso, un bastone ricavato da un albero vivente, un rametto di vischio o di agrifoglio, o un totem che includa piume,pelliccia, ossa e denti di qualche animale sacro. Un druido pub usare un oggetto del genere come focus da incantatore nel modo descritto nel capitolo 10.",0.5F,"10 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Bastone in Legno","Un focus druidico potrebbe essere una bacchetta o uno scettro fatto in legno di tasso, un bastone ricavato da un albero vivente, un rametto di vischio o di agrifoglio, o un totem che includa piume,pelliccia, ossa e denti di qualche animale sacro. Un druido pub usare un oggetto del genere come focus da incantatore nel modo descritto nel capitolo 10.",2F,"3 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Bilancia da Mercante"," Una bilancia è composta da un piccolo braccio, due piatti e un assortimento di pesi di varie misure fino a un massimo di 1 kg. Grazie a questa bilancia,un personaggio può misurare il peso esatto degli oggetti più piccoli, come per esempio i metalli preziosi allo stato grezzo o le merci, per determinarne il valore esatto",1.5F,"5 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Borsa"," Una borsa di stoffa o di cuoio può contenere fino a 20 proiettili da fionda o 50 aghi da cerbottana, tra le altre cose. Una borsa suddivisa in scomparti per contenere le componenti per incantesimi è chiamata una borsa per componenti (descritta di seguito).",0.5F,"5 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Borsa del guaritore","Questa borsa in pelJe contiene bende, unguenti e stecche di legno. Prevede dieci utilizzi.Con un'azione, un personaggio può spendere un utilizzo per stabilizzare una creatura scesa a O punti ferita senza dover effettuare una prova di Saggezza (Medicina)",1.5F,"5 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Borsa per Componenti","Una borsa per componenti è una piccola borsa di cuoio impermeabile da legare alla cintura, dotata di scomparti dove custodire tutte le componenti materiali e gli altri oggetti speciali di cui il personaggio ha bisogno per lanciare incantesimi, fatta eccezione per quelle componenti che prevedono un costo specifico (come indicato nella descrizione dell'incantesimo).",1F,"25 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Bottiglia di Vetro","Bottiglia di Vetro",1F,"2 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Brocca o Caraffa","Brocca o Caraffa",2F,"2 mr"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Campanella","Campanella",0F,"1 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Candela","Per 1 ora, una candela proietta luce intensa entro un raggio di lt5 metri e luce fioca per altri 1,5 metri.",0F,"1 mr"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Canestro","Canestro",1F,"4 ma"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Canna da Pesca","Questo oggetto include un'asta di legno, un filo di seta, un galleggiante di sughero, ami in acciaio, mosche da usare come esche e una reticella.",2F,"1 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Cannocchiale","Gli oggetti osservati attraverso un cannocchiale appaiono grandi il doppio della loro taglia",0.5F,"1000 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Carrucola e Paranco","Questa serie di carrucole è dotata di un cavo che le attraversa e che si collega a un uncino da agganciare a un oggetto. Consente a un personaggio di sollevare fino al quadruplo del peso che normalmente potrebbe sollevare. ",2.5F,"1 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Carta (un foglio)","Carta",0F,"1 ma"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Catena (3 metri)","Una catena ha 10 punti ferita. Può essere spezzata superando una prova di Forza con CD 20. ",5F,"5 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Cera per sigillo","Cera per sigillo",0F,"5 ma"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Chiodo da Rocciatore","Chiodo da Rocciatore",0.125F,"5 mr"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Clessidra","Clessidra",0.5F,"25 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Coperta","Coperta",1.5F,"5 ma"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Corda di canapa (15 metri)","Una corda, che sia di canapa o di seta, possiede 2punti ferita e può essere spezzata superando una prova diForza con CD 17.",5F,"1 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Corda di seta (15 metri)","Una corda, che sia di canapa o di seta, possiede 2punti ferita e può essere spezzata superando una prova diForza con CD 17.",2.5F,"10 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Cote per Affilare","Cote per Affilare",0.5F,"1 mr"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Cristallo"," Un focus arcano è un oggetto speciale(una bacchetta in legno, un bastone di fattura speciale,un cristallo, un globo, una verga), creato per incanalare il potere degli incantesimi arcani. Un mago, uno stregone o un warlock può usare questo oggetto come focus da incantatore nel modo descritto nel capitolo 10. ",0.5F,"10 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Custodia per mappe e pergamene","Questa custodia cilindrica in cuoio può contenere fino a dieci fogli di carta arrotolati o fino a cinque fogli di pergamena arrotolati",0.5F,"1 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Custodia per quadrelli da Balestra","Questa custodia in legno può contenere fino a 20 quadrelli da balestra",0.5F,"1 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Emblema","Un simbolo sacro è la rappresentazione di un dio o di un pantheon. Potrebbe essere un amuleto che raffigura il simbolo di una divinità, o uno scudo che porta quel simbolo inciso come emblema, o un minuscolo scrigno contenente il frammento di una reliquia sacra.L'appendice 8 elenca i simboli comunemente associati alla maggior parte delle divinità del multiverso. Un chierico o un paladino può usare un simbolo sacro come focus da incantatore, nel modo descritto nel capitolo 10. Per usare il simbolo in questo modo, l'incantatore deve impugnarlo in modo ben visibile o portarlo su uno scudo",0F,"5 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Faretra","Una faretra può contenere fino a 20 frecce.",0.5F,"1 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Fiala","Fiala",0F,"1 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Fischietto da richiamo","Fischietto da richiamo",0F,"5 mr"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Frecce (20)","Frecce",0.5F,"1 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Forziere","Forziere",12.5F,"5 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Fuoco dell'alchimista (ampolla)","Questo fluido adesivo e gommoso si infiamma quando è esposto all'aria. Con un'azione, il personaggio può lanciare questa ampolla fino 6 metri di distanza (rampolla si frantumerà all'impatto). li personaggio effettua un attacco a distanza contro una creatura o un oggetto, considerando il fuoco dell'alchimista come arma improvvisata. Se colpisce il bersaglio, esso subisce ld4 danni da fuoco all'inizio di ogni suo turno. Una creatura può terminare questi danni usando un'azione per effettuare una prova di Destrezza con CD 10 al fine di estinguere le fiamme. ",0.5F,"50 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Gavetta","Questa scatola di stagno contiene una scodella e delle semplici posate. Le due metà della scatola, una volta aperte, possono essere usate come padella e come piatto o scodella",0.5F,"2 ma"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Gessetto (1 pezzo)","Gessetto",0F,"1 mr"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Giaciglio","Giaciglio",1F,"3.5 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Globo"," Un focus arcano è un oggetto speciale(una bacchetta in legno, un bastone di fattura speciale,un cristallo, un globo, una verga), creato per incanalare il potere degli incantesimi arcani. Un mago, uno stregone o un warlock può usare questo oggetto come focus da incantatore nel modo descritto nel capitolo 10. ",1F,"20 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Inchiostro (boccetta da 30 grammi)","Una boccetta contenente 30 grammi di inchiostro",5F,"2 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Lampada","Una lampada proietta luce intensa in un raggio di 4,5 metri e luce fioca per ulteriori 9 metri. Una volta accesa,arde per 6 ore consumando 1 ampolla (0,5 litri) di olio. ",0.5F,"5 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Lanterna a lente sporgente","Una lanterna a lente sporgente proietta luce intensa in un cono di 18 metri e luce fioca per ulteriori 18 metri. Una volta accesa, arde per 6 ore consumando 1 ampolla (0,5 litri) di olio",5F,"2 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Lanterna schermabile","Una lanterna schermabile proietta luce intensa in un raggio di 9 metri e luce fioca per ulteriori9 metri. Una volta accesa, arde per 6 ore consumando 1ampolla (0,5 litri) di olio. Con un'azione, un personaggio può abbassare il cappuccio della lanterna, riducendo la luce proiettata a luce fioca in un raggio di 1,5 metri",1F,"5 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Lente d'ingrandimento","Questa lente consente di esaminare più da vicino gfi oggetti più piccoli. Può anche tornare utile come alternativa alla pietra focaia e all'acciarino per accendere un fuoco. Per accendere un fuoco con una lente d'ingrandimento è necessaria una luce da concentrare intensa quanto la luce del sole, dei rametti da accendere e circa 5 minuti affinché il fuoco attecchisca.Una lente d'ingrandimento conferisce vantaggio a ogni prova di caratteristica effettuata per valutare o ispezionare un oggetto di piccola taglia o estremamente dettagliato.",0F,"100 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Libro"," Un libro può contenere poesie, resoconti storici,informazioni in un campo specifico di conoscenze,diagrammi e appunti su un marchingegno gnomesco o pressoché ogni informazione che sia possibile trasmettere tramite testi e immagini. Se contiene incantesimi, si tratta di un libro degli incantesimi (descritto di seguito).",2.5F,"25 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Libro degli incantesimi",". Un libro degli incantesimi,essenziale per i maghi, è un tomo rilegato in cuoio e composto da 100 pagine pergamenate vuote su cui annotare gli incantesimi.",1.5F,"50 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Manette","Queste costrizioni di metallo possono bloccare una creatura di taglia Media o Piccola. Per sfuggire alle manette è necessario superare una prova di Destrezza con CD 20. A ogni coppia di manette è abbinata una chiave.Senza la chiave, una creatura competente negli arnesi da scasso può scassinare la serratura superando una prova diDestrezza con CD 15. Le manette hanno 15 punti ferita",3F,"2 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Martello","Martello",1.5F,"1 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Martello da demolizione","Martello da demolizione",5F,"2 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Olio (ampolla)","L'olio solitamente viene venduto in ampolle di argilla da 0,5 litri. Con un'azione, il personaggio può spruzzare l'olio del'ampolla su una creatura situata entro 1,5 metri da lui o lanciarla fino a 6 metri di distanza (l'ampolla si frantumerà all'impatto). li personaggio effettua un attacco a distanza contro una creatura o un oggetto, considerando l'olio come un'arma improvvisata. Se colpisce il bersaglio,lo ricopre di olio. Se il bersaglio subisce danni da fuoco prima che l'olio si asciughi (dopo 1 minuto), esso subisce5 danni da fuoco aggiuntivi a causa dell'olio incendiato.Un personaggio può anche versare un'ampolla di olio sul terreno per coprire un'area quadrata con lato di 1,5 metri,purché la superficie sia piana. Una volta incendiato, l'oliobrucia per 2 round e infligge 5 danni da fuoco a qualsiasicreatura che entri nell'area o vi termini il proprio turno. Unacreatura pub subire questi danni solo una volta per turno.",0.5F,"1 ma"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Otre","Otre",2.5F,"2 mr"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Pennino","Pennino",0F,"2 mr"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Pergamena (un foglio)","Pergamena",0F,"1 ma"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Piccone da Minatore","Piccone da Minatore",5F,"2 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Piede di Porco","L'utilizzo di un piede di porco conferisce vantaggio alle prove di Forza in cui è possibile usare il piede di porco per fare leva.",2.5F,"2 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Pozione di guarigione","Quando un personaggio beve il druido magico rosso contenuto in questa fiala recupera 2d4 + 2 punti ferita. Per bere o somministrare una pozione è richiesta un'azione. ",0.25F,"50 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Profumo (fiala)","Profumo",0F,"5 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Proiettili da fionda (20)","Proiettili da fionda",0.75F,"4 mr"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Quadrelli da Balestra","Quadrelli da Balestra",0.75F,"1 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Rametto di vischio","Un focus druidico potrebbe essere una bacchetta o uno scettro fatto in legno di tasso, un bastone ricavato da un albero vivente, un rametto di vischio o di agrifoglio, o un totem che includa piume,pelliccia, ossa e denti di qualche animale sacro. Un druido pub usare un oggetto del genere come focus da incantatore nel modo descritto nel capitolo 10.",0F,"1 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Rampino","Rampino",2F,"2 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Razioni (1 giornata)"," Le razioni consistono in cibo essiccato adatto a essere trasportato nei lunghi viaggi: carne secca, frutta secca, gallette e noci",1F,"5 ma"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Reliquario","Un simbolo sacro è la rappresentazione di un dio o di un pantheon. Potrebbe essere un amuleto che raffigura il simbolo di una divinità, o uno scudo che porta quel simbolo inciso come emblema, o un minuscolo scrigno contenente il frammento di una reliquia sacra.L'appendice 8 elenca i simboli comunemente associati alla maggior parte delle divinità del multiverso. Un chierico o un paladino può usare un simbolo sacro come focus da incantatore, nel modo descritto nel capitolo 10. Per usare il simbolo in questo modo, l'incantatore deve impugnarlo in modo ben visibile o portarlo su uno scudo",1F,"5 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Sacco","Sacco",10F,"1 mr"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Sapone","Sapone",0F,"2 mr"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Scala a Pioli (3 metri)","Scala a Pioli",12.5F,"1 ma"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Secchio","Secchio",1F,"5 mr"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Serratura","Assieme alla serratura viene fornita una chiave. Senza la chiave, una creatura competente negli arnesi da scasso può scassinare la serratura superando una prova di Destrezza con CD 15. Il DM può permettere che siano disponibili serrature migliori a prezzi più alti. ",0.5F,"10 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Sfere Metalliche (sacchetto da 1.000)"," Con un'azione, un personaggi o può versare queste minuscole sfere di metallo fuori dal sacchetto per coprire un'area quadrata regolare e. pianeggiante con lato di 3 metri. Quando una creatura si muove attraverso l'area coperta dalle sfere, deve superare un tiro salvezza su Destrezza con CD 10, altrimenti cade a terra prona. Se una creatura si muove attraverso l'area a velocità dimezzata, non deve effettuare il tiro salvezza.",1F,"1 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Specchio Piccolo di Metallo","Specchio Piccolo di Metallo",0.25F,"5 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Spuntoni, Ferro (10)","Spuntoni, Ferro",5F,"1 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Tagliola","Quando il personaggio usa la sua azione per predisporre questa trappola, colloca a terra un cerchio di metallo dentato che si chiude con uno scatto quando una creatura preme una leva d'aggancio situata al centro. La trappola viene fissata a una pesante catena o a un oggetto immobile come un albero o un palo piantato a terra. Quando una creatura mette un piede sulla leva, deve superare un tiro salvezza su Destrezza con CD 13, altrimenti subisce ld4danni perforanti e smette di muoversi. Da allora in poi, finché la creatura non si libera dalla trappola, il suo movimento è limitato dalla lunghezza della catena (solitamente 90 cm). Una creatura può usare la sua azione per effettuare una prova di forza con CD 13 per liberare se stessa o un'altra creatura entro portata in caso di successo. Ogni prova fallita infligge1 danno perforante alla creatura intrappolata. ",12.5F,"5 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Tenda per due persone","Un semplice riparo portatile in tela, che può ospitare due persone",10F,"2 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Torcia","Una torcia arde per 1 ora e proietta luce intensa in un raggio di 6 metri e luce fioca per ulteriori 6 metri.Se un personaggio effettua un attacco in mischia con una torcia accesa e colpisce, infligge 1 danno da fuoco. ",0.5F,"1 mr"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Totem","Un focus druidico potrebbe essere una bacchetta o uno scettro fatto in legno di tasso, un bastone ricavato da un albero vivente, un rametto di vischio o di agrifoglio, o un totem che includa piume,pelliccia, ossa e denti di qualche animale sacro. Un druido pub usare un oggetto del genere come focus da incantatore nel modo descritto nel capitolo 10.",0F,"1 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Triboli (sacchetto da 20)",". Con un'azione, un personaggio può spargere il contenuto di un sacchetto di triboli per coprire un'areaQuadrata con lato di 1,5 metri. Ogni creatura che entra in quell'area deve superare un tiro salvezza su Destrezza conCD 15, altrimenti dovrà smettere di muoversi per questo turno e subire 1 danno perforante. Se subisce questo danno, la sua velocità base sul terreno è ridotta di 3 metri finché non recupera almeno 1 punto ferita. Se una creatura si muove attraverso l'area a velocità dimezzata, non deve effettuare il tiro salvezza. ",1F,"1 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Vanga o Badile","Vanga o Badile",2.5F,"2 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Vaso di Ferro","Vaso di Ferro",5F,"2 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Veleno, base (fiala)","Un personaggio può usare il veleno contenuto in questa fiala per rivestire un'arma tagliente o perforante o un massimo di tre munizioni. Per applicare il veleno è richiesta un'azione. Una creatura colpita dall'arma o dalle munizioni avvelenate deve superare un tiro salvezza su Costituzione con CD 10, altrimenti subirà ld4 danni da veleno. Una volta applicato, il veleno mantiene la sua potenza per 1 minuto prima di essiccarsi",0F,"100 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Verga"," Un focus arcano è un oggetto speciale(una bacchetta in legno, un bastone di fattura speciale,un cristallo, un globo, una verga), creato per incanalare il potere degli incantesimi arcani. Un mago, uno stregone o un warlock può usare questo oggetto come focus da incantatore nel modo descritto nel capitolo 10. ",1F,"10 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Veste","Veste da indossare",2F,"1 mo"));
        this.dizionarioEquipaggiamento.add(new Equipaggiamento("Zaino","Zaino per contenere l'equipaggiamento",2.5F,"2 mo"));

        //String nomeEquipaggiamento, String descrizione, float peso, String costo
    }

    public TreeSet<Equipaggiamento> getDizionarioEquipaggiamento() {
        return dizionarioEquipaggiamento;
    }
}
